//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("resources/cave2.jpg")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("resources/combatbox.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("resources/combatenemy_1.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("resources/combatenemy_2.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("resources/combatplayer.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("resources/combatwitch.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("resources/combatwitchblue.png")]


